name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ronirola/gauge-service-test:latest .
          docker push ronirola/gauge-service-test:latest

      - name: Debugging Information
        run: |
          docker run ronirola/gauge-service-test:latest ls -la /app
          docker run ronirola/gauge-service-test:latest gauge -v
          docker run ronirola/gauge-service-test:latest java -version
          docker run ronirola/gauge-service-test:latest echo $PATH

      - name: Run tests
        run: |
          docker run ronirola/gauge-service-test:latest sh -c "Xvfb :99 -ac & mvn gauge:execute -e -X"
